"""OpenAPI 3.0 → pytest 数据驱动契约用例生成器。

用法:
    python tools/openapi_gen.py openapi.yaml -o tests/api/generated

按 tag 分组生成 test_<tag>.py，每个 operation 生成一个参数化契约用例，
覆盖: 必填参数、请求体示例、期望状态码、响应 JSON Schema 校验。
生成文件标注 AUTO-GENERATED，可随时重新生成覆盖。
"""
from __future__ import annotations

import argparse
from pathlib import Path
from pprint import pformat

import yaml

MODULE_HEADER = '''\
# AUTO-GENERATED by openapi_gen.py — 请勿手改，重新生成即可
# api_client 为 pytest fixture，定义于 tests/conftest.py
import allure
import pytest
import jsonschema

pytestmark = pytest.mark.api

VERBS = {{"POST": "创建", "GET": "查询", "PUT": "更新", "PATCH": "更新", "DELETE": "删除"}}


def _title(case) -> str:
    return VERBS.get(case["method"], case["method"]) + " " + case["path"]


CASES = {cases}


@allure.feature("{tag}")
@allure.story("契约测试")
@pytest.mark.parametrize("case", CASES, ids=_title)
def test_{func_name}_contract(api_client, case):
    \"\"\"{summary}\"\"\"
    allure.dynamic.title(_title(case))
    with allure.step("发起 " + case["method"] + " " + case["path"]):
        resp = api_client.request(
            case["method"], case["path"],
            params=case["params"], json=case["json"],
        )
    with allure.step("校验状态码"):
        api_client.mark_expect(case["expected_codes"], resp.status_code, resp.text)
        assert resp.status_code in case["expected_codes"], (
            str(resp.status_code) + ": " + resp.text
        )
    if case.get("schema"):
        with allure.step("校验响应 JSON Schema"):
            jsonschema.validate(resp.json(), case["schema"])
    allure.attach(resp.text, "响应体", allure.attachment_type.JSON)
'''


def _resolve(spec: dict, schema: dict) -> dict:
    """沿 $ref 链解析到实际 schema（仅支持本文件内 #/components/schemas 引用）。"""
    seen: set[str] = set()
    while isinstance(schema, dict) and "$ref" in schema:
        ref = schema["$ref"]
        if ref in seen or not ref.startswith("#/components/schemas/"):
            break
        seen.add(ref)
        schema = spec["components"]["schemas"][ref.rsplit("/", 1)[1]]
    return schema


def _example_for(spec: dict, schema: dict):
    """为 schema 生成示例值：example > default > enum 首值 > 按类型。"""
    schema = _resolve(spec, schema)
    if "example" in schema:
        return schema["example"]
    if "default" in schema:
        return schema["default"]
    t = schema.get("type")
    if t == "string":
        return schema["enum"][0] if schema.get("enum") else "<string>"
    if t == "integer":
        return schema["enum"][0] if schema.get("enum") else 0
    if t == "number":
        return 0.0
    if t == "boolean":
        return False
    if t == "array":
        return [_example_for(spec, schema.get("items", {}))]
    if t == "object":
        return {k: _example_for(spec, v) for k, v in schema.get("properties", {}).items()}
    return None


def _response_schema(spec: dict, op: dict) -> dict | None:
    for code in _success_codes(op):
        content = op["responses"][str(code)].get("content", {}).get("application/json", {})
        if "schema" in content:
            return _resolve(spec, content["schema"])
    return None


def _success_codes(op: dict) -> list[int]:
    return [int(c) for c in op.get("responses", {}) if c.startswith("2")] or [200]


def _build_case(spec: dict, method: str, path: str, op: dict) -> dict:
    path_vars: dict[str, str] = {}
    params: dict[str, object] = {}
    for p in op.get("parameters", []):
        name, loc = p.get("name"), p.get("in")
        value = _example_for(spec, p.get("schema", {}))
        if loc == "path":
            path_vars[name] = str(value)
        elif loc == "query" and p.get("required"):
            params[name] = value
    for name, value in path_vars.items():
        path = path.replace("{" + name + "}", value)
    body_schema = (
        op.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema")
    )
    return {
        "method": method.upper(),
        "path": path,
        "params": params or None,
        "json": _example_for(spec, body_schema) if body_schema else None,
        "expected_codes": _success_codes(op),
        "schema": _response_schema(spec, op),
    }


def _safe_name(name: str) -> str:
    cleaned = "".join(c if c.isalnum() else "_" for c in name).strip("_").lower()
    return cleaned or "default"


def generate(spec_path: Path, out_dir: Path) -> int:
    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    by_tag: dict[str, list[dict]] = {}
    for path, path_item in spec.get("paths", {}).items():
        for method, op in path_item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            tag = (op.get("tags") or ["default"])[0]
            by_tag.setdefault(tag, []).append(_build_case(spec, method, path, op))

    out_dir.mkdir(parents=True, exist_ok=True)
    total = 0
    skipped = []
    for tag, cases in by_tag.items():
        out_file = out_dir / f"test_{_safe_name(tag)}.py"
        if out_file.exists() and "手写维护" in out_file.read_text(encoding="utf-8")[:200]:
            skipped.append(out_file.name)
            continue
        module = MODULE_HEADER.format(
            cases=pformat(cases),
            func_name=_safe_name(tag),
            tag=tag,
            summary=f"{tag} 接口契约",
        )
        out_file.write_text(module, encoding="utf-8")
        total += len(cases)
    if skipped:
        print("SKIP 手写维护文件（不覆盖）: " + ", ".join(skipped))
    return total


def main() -> None:
    parser = argparse.ArgumentParser(description="OpenAPI → pytest 契约用例生成器")
    parser.add_argument("spec", type=Path, help="OpenAPI 3.0 规范文件 (yaml/json)")
    parser.add_argument("-o", "--out", type=Path, default=Path("tests/api/generated"),
                        help="输出目录")
    args = parser.parse_args()

    count = generate(args.spec, args.out)
    print(f"OK 生成 {count} 个契约用例 -> {args.out}")


if __name__ == "__main__":
    main()
