"""确定性渲染器：把「用例声明 JSON」渲染成 pytest ApiCase 脚本（方向 A）。

设计核心（2026-09-01 确立）：LLM 只输出受 JSON Schema 约束的**声明数据**
（接口/字段/断言/业务码引用/save/清理），本模块用固定模板把声明**确定性**
渲染成 pytest 源码。op 白名单、_bf 语法、pytestmark、save/清理逻辑全部由
模板保证 —— 物理上不存在「AI 发明不支持的 op / 写错语法 / 写错字段」的可能，
从架构上消除"无穷打补丁"。

被测系统解耦：marker / 业务码表 / 角色 / fixture 全部取自 SystemProfile 画像。
"""
from __future__ import annotations

import pprint

from app.services.system_profile import SystemProfile

# 断言引擎支持的操作符白名单（与被测工程 support/api_case.py::_eval 严格一致）
VALID_OPS = {"eq", "ne", "exists", "contains", "in", "gt", "gte", "lt", "lte", "regex"}

# 业务失败反例辅助函数模板（探测不到业务码时退化为 msg 存在并打印显式警告）
_BF_HELPER = '''def _bf(key):
    """动态业务失败断言：探测不到业务码时退化为「msg 存在」断言，避免导入期 None 崩溃。"""
    code = SA_CODES.get(key)
    if code is None:
        print(f"[反例断言降级] 业务码 {key} 未探测到，仅校验 /msg 存在（反例可能白测，请核对）")
        return [Assertion(expected=True, op="exists", field="/msg",
                          reason=f"业务码 {key} 未探测到，退化为仅校验失败信封")]
    return Assertion.biz_fail(code=code) + [Assertion(expected=True, op="exists", field="/msg")]
'''


def _p(obj) -> str:
    """对象 → Python 字面量（pprint 保留中文、缩进可读）。"""
    if obj is None:
        return "None"
    return pprint.pformat(obj, width=100)


def _fmt_assertion(a: dict) -> str:
    args = []
    if a.get("field"):
        args.append(f'field={a["field"]!r}')
    args.append(f'op={a["op"]!r}')
    if "expected" in a:
        args.append(f"expected={a['expected']!r}")
    elif a.get("op") == "exists":
        # Assertion.expected 是必填位置参数，exists 语义无预期值 → 兜底 expected=True
        args.append("expected=True")
    if a.get("reason"):
        args.append(f'reason={a["reason"]!r}')
    return "Assertion(" + ", ".join(args) + ")"


def _fmt_api_case(c: dict, has_codes: bool) -> str:
    args = [f'name={c["name"]!r}', f'method={c["method"]!r}', f'path={c["path"]!r}']
    if c.get("body"):
        args.append(f"body={_p(c['body'])}")
    if c.get("params"):
        args.append(f"params={_p(c['params'])}")
    if c.get("save"):
        args.append(f"save={_p(c['save'])}")
    if c.get("biz_fail"):
        # 业务失败反例：biz_auto=False + 解包 _bf("key")（动态业务码，探测不到退化为 msg 存在并打印警告）
        args.append("biz_auto=False")
        if has_codes:
            args.append(f'assertions=[*_bf({c["biz_fail"]!r})]')
        else:
            # 无业务码表的被测工程：退化为仅校验失败信封存在
            args.append("assertions=[Assertion(expected=True, op=\"exists\", field=\"/msg\")]")
    else:
        if "biz_auto" in c:
            args.append(f"biz_auto={str(bool(c['biz_auto']))}")
        if c.get("assertions"):
            args.append("assertions=[" + ", ".join(_fmt_assertion(a) for a in c["assertions"]) + "]")
    return "ApiCase(" + ", ".join(args) + ")"


def render_code(spec: dict, profile: SystemProfile) -> str:
    """把声明 spec 渲染成可落盘的 pytest 源码字符串。

    渲染产物由模板保证语法正确；调用方仍可再用 _lint_code 做 compile 兜底（防御性）。
    """
    module = spec.get("module", "module")
    steps: list[dict] = spec.get("steps", [])
    uses_roles = any(s.get("role") for s in steps)
    has_bf = any(s.get("biz_fail") for s in steps)
    has_codes = bool(profile.codes_import)
    cleanups = {s["name"]: s["cleanup"] for s in steps if s.get("cleanup")}

    out: list[str] = []
    out.append('"""')
    out.append("AUTO-GENERATED by pytest-case-generator (declarative renderer)")
    out.append("Source mapping:")
    for s in steps:
        out.append(f"{s['name']} -> {s['name']}")
    out.append('"""')

    # ---- imports ----
    imp = ["from __future__ import annotations", "", "import allure", "import pytest"]
    if uses_roles:
        imp.append("from support.api_case import ApiCase, Assertion, FlowStep, run_case")
        imp.append("from support.clients.api_client import ApiClient")
    else:
        imp.append("from support.api_case import ApiCase, Assertion, run_case")
    imp.append("from support.fixtures.context import ScenarioContext")
    if has_bf and has_codes:
        imp.append(profile.codes_import)
    out.append("\n".join(imp))

    # ---- _bf helper（仅当存在业务失败反例） ----
    if has_bf and has_codes:
        out.append("\n\n" + _BF_HELPER.strip())

    # ---- 资源清理表（创建类用例按声明注册清理） ----
    if cleanups:
        out.append("\n\n# 创建类用例的资源清理规则（渲染器按声明生成）")
        out.append("_CLEANUP = " + _p(cleanups))

    # ---- pytestmark ----
    markers = []
    if profile.marker:
        markers.append(f"pytest.mark.{profile.marker}")
    markers.append("pytest.mark.api")
    if uses_roles:
        for r in (spec.get("pytestmark_roles") or []):
            markers.append(f"pytest.mark.requires_role('{r}')")
    out.append("\n\npytestmark = [" + ", ".join(markers) + "]")

    # ---- CASES / FLOW_STEPS ----
    if uses_roles:
        out.append("\n\nFLOW_STEPS: list[FlowStep] = [")
        for s in steps:
            out.append(f"    FlowStep({s.get('role')!r}, {_fmt_api_case(s, has_codes)}),")
        out.append("]")
    else:
        out.append("\n\nCASES: list[ApiCase] = [")
        for s in steps:
            out.append("    " + _fmt_api_case(s, has_codes) + ",")
        out.append("]")

    # ---- 测试函数（固定模板，清理逻辑由 _CLEANUP 表驱动） ----
    feature = spec.get("feature") or f"{profile.system_name} · {module}"
    story = spec.get("story") or "L2 接口"
    cleanup_block = """    if result.passed and case.name in _CLEANUP:
        rule = _CLEANUP[case.name]
        cid = ctx.get(rule["id_var"])
        if cid is not None:
            cleanup_registry.register_delete(rule["delete_path"], cid)"""
    if uses_roles:
        cleanup_block = cleanup_block.replace("case.name", "step.case.name").replace(
            "_CLEANUP[case.name]", "_CLEANUP[step.case.name]")
        fn = f'''
@allure.feature({feature!r})
@allure.story({story!r})
@pytest.mark.parametrize("step", FLOW_STEPS, ids=lambda s: s.case.name)
def test_{module}_role_flow(role_registry, ctx: ScenarioContext, cleanup_registry, base_url, admin_client, step: FlowStep):
    if step.role == "anonymous":
        client = ApiClient(base_url)
    elif step.role == "admin":
        client = admin_client
    else:
        client = role_registry[step.role]
    result = run_case(client, ctx, step.case)
{cleanup_block}
    assert result.passed, f"[{{step.role}}] {{step.case.name}}: {{result.failure_summary}}"
'''
    else:
        fn = f'''
@allure.feature({feature!r})
@allure.story({story!r})
@pytest.mark.parametrize("case", CASES, ids=lambda c: c.name)
def test_{module}_crud(api_client, ctx: ScenarioContext, cleanup_registry, case: ApiCase):
    result = run_case(api_client, ctx, case)
{cleanup_block}
    assert result.passed, f"[{{case.name}}] {{result.failure_summary}}"
'''
    out.append(fn)

    return "\n".join(out).strip() + "\n"
