# AUTO-GENERATED by testcase-to-pytest transformer
# Source cases mapping:
# TC-ENTERPRISE-01 -> 管理员成功分页查询企业列表
# TC-ENTERPRISE-02 -> 管理员使用关键字模糊查询企业
# TC-ENTERPRISE-03 -> 管理员使用创建时间范围查询企业
# TC-ENTERPRISE-04 -> 管理员使用禁用状态筛选企业
# TC-ENTERPRISE-05 -> 管理员分页查询，每页数量超过500
# TC-ENTERPRISE-06 -> 未登录用户尝试查询企业列表
# TC-ENTERPRISE-07 -> 普通员工（无权限）尝试查询企业列表
# TC-ENTERPRISE-08 -> 管理员成功查询企业详情
# TC-ENTERPRISE-09 -> 查询不存在或已删除的企业详情
# TC-ENTERPRISE-10 -> 未登录用户尝试查询企业详情
# TC-ENTERPRISE-11 -> 普通员工（无权限）尝试查询企业详情
# TC-ENTERPRISE-12 -> 管理员成功新建企业
# TC-ENTERPRISE-13 -> 新建企业时企业名称重复
# TC-ENTERPRISE-14 -> 新建企业时缺少必填字段
# TC-ENTERPRISE-15 -> 新建企业时联系人电话格式错误
# TC-ENTERPRISE-16 -> 新建企业时邮箱格式错误
# TC-ENTERPRISE-17 -> 未登录用户尝试新建企业
# TC-ENTERPRISE-18 -> 普通员工（无权限）尝试新建企业
# TC-ENTERPRISE-19 -> 管理员成功编辑企业
# TC-ENTERPRISE-20 -> 编辑企业时修改的名称与其他企业重复
# TC-ENTERPRISE-21 -> 编辑不存在或已删除的企业
# TC-ENTERPRISE-22 -> 编辑企业时缺少必填字段
# TC-ENTERPRISE-23 -> 未登录用户尝试编辑企业
# TC-ENTERPRISE-24 -> 普通员工（无权限）尝试编辑企业
# TC-ENTERPRISE-25 -> 管理员成功删除企业
# TC-ENTERPRISE-26 -> 删除企业后，可新建同名企业
# TC-ENTERPRISE-27 -> 删除不存在或已删除的企业
# TC-ENTERPRISE-28 -> 未登录用户尝试删除企业
# TC-ENTERPRISE-29 -> 普通员工（无权限）尝试删除企业
# TC-ENTERPRISE-30 -> 管理员按类型查询企业列表（供下拉用）
# TC-ENTERPRISE-31 -> 管理员不传类型参数查询企业列表
# TC-ENTERPRISE-32 -> 未登录用户尝试查询企业列表（下拉用）
# TC-ENTERPRISE-33 -> 普通员工（无权限）尝试查询企业列表（下拉用）
# TC-ENTERPRISE-34 -> 管理员成功导出企业信息Excel
# TC-ENTERPRISE-35 -> 导出企业信息Excel时无符合条件数据
# TC-ENTERPRISE-36 -> 未登录用户尝试导出企业信息
# TC-ENTERPRISE-37 -> 管理员成功为企业添加员工
# TC-ENTERPRISE-38 -> 添加员工时，员工已在该企业下（幂等）
# TC-ENTERPRISE-39 -> 为不存在或已删除的企业添加员工
# TC-ENTERPRISE-40 -> 添加员工时，员工列表为空
# TC-ENTERPRISE-41 -> 管理员查询企业全部员工
# TC-ENTERPRISE-42 -> 查询企业全部员工时，企业ID列表为空
# TC-ENTERPRISE-43 -> 管理员分页查询企业员工
# TC-ENTERPRISE-44 -> 分页查询企业员工时，使用关键字搜索
# TC-ENTERPRISE-45 -> 管理员成功从企业移除员工
# TC-ENTERPRISE-46 -> 从不存在或已删除的企业移除员工
# TC-ENTERPRISE-47 -> 移除员工时，员工列表为空
# TC-ENTERPRISE-48 -> 未登录用户尝试添加/查询/移除企业员工
# TC-ENTERPRISE-49 -> 普通员工（无权限）尝试添加/查询/移除企业员工

from __future__ import annotations
import allure, pytest
from support.api_case import ApiCase, Assertion, FlowStep, run_case
from support.clients.api_client import ApiClient
from support.fixtures.context import ScenarioContext
from support.fixtures.smartadmin import SA_CODES

# 辅助函数：生成反例断言（业务码可能未探测到，降级处理）
def _bf(key):
    code = SA_CODES.get(key)
    if code is None:
        print(f"[反例断言降级] 业务码 {key} 未探测到，仅校验 /msg 存在（反例可能白测，请核对）")
        return [Assertion(expected=True, op="exists", field="/msg")]
    return Assertion.biz_fail(code=code) + [Assertion(expected=True, op="exists", field="/msg")]

# 角色标记：admin, employee, anonymous
pytestmark = [
    pytest.mark.smartadmin,
    pytest.mark.api,
    pytest.mark.requires_role('admin'),
    pytest.mark.requires_role('employee')
]

# 企业创建后的临时名称（避免冲突）
ENTERPRISE_NAME = "自动化测试企业"

# 测试用例流
FLOW_STEPS = [
    # 1. 创建企业（admin）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-12-管理员成功新建企业",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": ENTERPRISE_NAME,
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        assertions=[]
    )),
    # 2. 分页查询企业（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-01-管理员成功分页查询企业列表",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10},
        # 字段路径不确定，退化为exists
        assertions=[Assertion(expected=True, op="exists", field="/data/list")]
    )),
    # 3. 关键字查询（admin）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-02-管理员使用关键字模糊查询企业",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10, "keywords": ENTERPRISE_NAME},
        assertions=[Assertion(expected=True, op="exists", field="/data/list")]
    )),
    # 4. 时间范围查询（admin）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-03-管理员使用创建时间范围查询企业",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10, "startTime": "2023-01-01", "endTime": "2023-12-31"},
        assertions=[Assertion(expected=True, op="exists", field="/data/list")]
    )),
    # 5. 禁用状态筛选（admin）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-04-管理员使用禁用状态筛选企业",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10, "disabledFlag": False},
        assertions=[Assertion(expected=True, op="exists", field="/data/list")]
    )),
    # 6. 每页数量超限（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-05-管理员分页查询，每页数量超过500",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 501},
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 7. 未登录查询（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-06-未登录用户尝试查询企业列表",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10},
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 8. 普通员工查询（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-07-普通员工（无权限）尝试查询企业列表",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10},
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 9. 查询企业详情（admin）正例 - 需先获取enterpriseId
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-01-分页反查id",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10, "keywords": ENTERPRISE_NAME},
        save={"/data/list[0]/enterpriseId": "enterprise_id"},
        assertions=[]
    )),
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-08-管理员成功查询企业详情",
        method="GET",
        path="/oa/enterprise/get/${enterprise_id}",
        # 字段路径不确定，退化为exists
        assertions=[Assertion(expected=True, op="exists", field="/data/enterpriseId")]
    )),
    # 10. 查询不存在企业详情（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-09-查询不存在或已删除的企业详情",
        method="GET",
        path="/oa/enterprise/get/99999",
        biz_auto=False,
        assertions=[*_bf("enterprise_not_exist")]
    )),
    # 11. 未登录查询详情（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-10-未登录用户尝试查询企业详情",
        method="GET",
        path="/oa/enterprise/get/${enterprise_id}",
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 12. 普通员工查询详情（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-11-普通员工（无权限）尝试查询企业详情",
        method="GET",
        path="/oa/enterprise/get/${enterprise_id}",
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 13. 编辑企业（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-19-管理员成功编辑企业",
        method="POST",
        path="/oa/enterprise/update",
        body={
            "enterpriseId": "${enterprise_id}",
            "enterpriseName": ENTERPRISE_NAME + "_更新",
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "李四",
            "contactPhone": "13900139000",
            "disabledFlag": False
        },
        assertions=[]
    )),
    # 14. 编辑企业名称重复（反例）- 需要先有另一个企业
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-20-编辑企业时修改的名称与其他企业重复",
        method="POST",
        path="/oa/enterprise/update",
        body={
            "enterpriseId": "${enterprise_id}",
            "enterpriseName": "系统已存在的企业名称",  # 假设存在
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("enterprise_name_duplicate")]
    )),
    # 15. 编辑不存在企业（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-21-编辑不存在或已删除的企业",
        method="POST",
        path="/oa/enterprise/update",
        body={
            "enterpriseId": 99999,
            "enterpriseName": "任意名称",
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("enterprise_not_exist")]
    )),
    # 16. 编辑缺少必填字段（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-22-编辑企业时缺少必填字段",
        method="POST",
        path="/oa/enterprise/update",
        body={
            "enterpriseId": "${enterprise_id}",
            "enterpriseName": "",  # 空名称
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 17. 未登录编辑（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-23-未登录用户尝试编辑企业",
        method="POST",
        path="/oa/enterprise/update",
        body={
            "enterpriseId": "${enterprise_id}",
            "enterpriseName": "任意名称",
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 18. 普通员工编辑（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-24-普通员工（无权限）尝试编辑企业",
        method="POST",
        path="/oa/enterprise/update",
        body={
            "enterpriseId": "${enterprise_id}",
            "enterpriseName": "任意名称",
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 19. 按类型查询列表（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-30-管理员按类型查询企业列表",
        method="GET",
        path="/oa/enterprise/query/list",
        params={"type": 1},
        assertions=[Assertion(expected=True, op="exists", field="/data")]
    )),
    # 20. 不传类型查询（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-31-管理员不传类型参数查询企业列表",
        method="GET",
        path="/oa/enterprise/query/list",
        assertions=[Assertion(expected=True, op="exists", field="/data")]
    )),
    # 21. 未登录查询列表（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-32-未登录用户尝试查询企业列表",
        method="GET",
        path="/oa/enterprise/query/list",
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 22. 普通员工查询列表（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-33-普通员工（无权限）尝试查询企业列表",
        method="GET",
        path="/oa/enterprise/query/list",
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 23. 导出Excel（admin）正例 - 无具体断言，仅验证接口可达
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-34-管理员成功导出企业信息Excel",
        method="POST",
        path="/oa/enterprise/exportExcel",
        body={"keywords": ENTERPRISE_NAME},
        biz_auto=False,
        assertions=[]
    )),
    # 24. 导出Excel无数据（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-35-导出企业信息Excel时无符合条件数据",
        method="POST",
        path="/oa/enterprise/exportExcel",
        body={"keywords": "不存在的企业名称XYZ"},
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 25. 未登录导出（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-36-未登录用户尝试导出企业信息",
        method="POST",
        path="/oa/enterprise/exportExcel",
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 26. 企业员工管理 - 添加员工（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-37-管理员成功为企业添加员工",
        method="POST",
        path="/oa/enterprise/employee/add",
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": [1, 2]  # 假设存在未关联的员工ID
        },
        assertions=[]
    )),
    # 27. 添加员工幂等（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-38-添加员工时，员工已在该企业下",
        method="POST",
        path="/oa/enterprise/employee/add",
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": [1]  # 重复添加同一员工
        },
        assertions=[]
    )),
    # 28. 为不存在企业添加员工（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-39-为不存在或已删除的企业添加员工",
        method="POST",
        path="/oa/enterprise/employee/add",
        body={
            "enterpriseId": 99999,
            "employeeIdList": [1]
        },
        biz_auto=False,
        assertions=[*_bf("enterprise_not_exist")]
    )),
    # 29. 员工列表为空（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-40-添加员工时，员工列表为空",
        method="POST",
        path="/oa/enterprise/employee/add",
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": []
        },
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 30. 查询企业全部员工（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-41-管理员查询企业全部员工",
        method="POST",
        path="/oa/enterprise/employee/queryPage",
        body={"pageNum":1,"pageSize":10,"enterpriseId":"${enterprise_id}","keyword":""},
        assertions=[Assertion(expected=True, op="exists", field="/data")]
    )),
    # # 31. 查询空列表（admin）正例
    # FlowStep("admin", ApiCase(
    #     name="TC-ENTERPRISE-42-查询企业全部员工时，企业ID列表为空",
    #     method="POST",
    #     path="/oa/enterprise/employee/list",
    #     body={"enterpriseIdList": []},
    #     biz_auto=False,
    #     assertions=[Assertion(expected=[], op="eq", field="/data")]
    # )),
    # 32. 分页查询企业员工（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-43-管理员分页查询企业员工",
        method="POST",
        path="/oa/enterprise/employee/queryPage",
        body={
            "enterpriseId": "${enterprise_id}",
            "pageNum": 1,
            "pageSize": 10
        },
        assertions=[Assertion(expected=True, op="exists", field="/data/list")]
    )),
    # 33. 关键字搜索员工（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-44-分页查询企业员工时，使用关键字搜索",
        method="POST",
        path="/oa/enterprise/employee/queryPage",
        body={
            "enterpriseId": "${enterprise_id}",
            "pageNum": 1,
            "pageSize": 10,
            "keyword": "测试"
        },
        assertions=[Assertion(expected=True, op="exists", field="/data/list")]
    )),
    # 34. 删除员工（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-45-管理员成功从企业移除员工",
        method="POST",
        path="/oa/enterprise/employee/delete",
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": [1]  # 移除之前添加的员工
        },
        assertions=[]
    )),
    # 35. 从不存在企业删除员工（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-46-从不存在或已删除的企业移除员工",
        method="POST",
        path="/oa/enterprise/employee/delete",
        body={
            "enterpriseId": 99999,
            "employeeIdList": [1]
        },
        biz_auto=False,
        assertions=[*_bf("enterprise_not_exist")]
    )),
    # 36. 员工列表为空删除（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-47-移除员工时，员工列表为空",
        method="POST",
        path="/oa/enterprise/employee/delete",
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": []
        },
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 37. 未登录操作员工接口（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-48-未登录用户尝试添加/查询/移除企业员工",
        method="POST",
        path="/oa/enterprise/employee/add",  # 以add为例，其他接口同样权限控制
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": [1]
        },
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 38. 普通员工操作员工接口（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-49-普通员工（无权限）尝试添加/查询/移除企业员工",
        method="POST",
        path="/oa/enterprise/employee/add",
        body={
            "enterpriseId": "${enterprise_id}",
            "employeeIdList": [1]
        },
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 39. 删除企业（admin）正例 - 放在最后
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-25-管理员成功删除企业",
        method="GET",
        path="/oa/enterprise/delete/${enterprise_id}",
        assertions=[]
    )),
    # 40. 删除后新建同名企业（admin）正例
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-26-删除企业后，可新建同名企业",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": ENTERPRISE_NAME,
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        assertions=[]
    )),
    # 41. 删除不存在企业（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-27-删除不存在或已删除的企业",
        method="GET",
        path="/oa/enterprise/delete/99999",
        biz_auto=False,
        assertions=[*_bf("enterprise_not_exist")]
    )),
    # 42. 未登录删除（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-28-未登录用户尝试删除企业",
        method="GET",
        path="/oa/enterprise/delete/1",
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 43. 普通员工删除（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-29-普通员工（无权限）尝试删除企业",
        method="GET",
        path="/oa/enterprise/delete/1",
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 44. 新建企业名称重复（反例）- 依赖第40步创建的企业
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-13-新建企业时企业名称重复",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": ENTERPRISE_NAME,
            "unifiedSocialCreditCode": "91110108MA01XXXX1",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("enterprise_name_duplicate")]
    )),
    # 45. 新建缺少必填字段（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-14-新建企业时缺少必填字段",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": "",
            "unifiedSocialCreditCode": "91110108MA01XXXX2",
            "type": 1,
            "contact": "李四",
            "contactPhone": "13900139000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 46. 新建电话格式错误（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-15-新建企业时联系人电话格式错误",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": "测试电话格式错误",
            "unifiedSocialCreditCode": "91110108MA01XXXX3",
            "type": 1,
            "contact": "张三",
            "contactPhone": "12345abc",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 47. 新建邮箱格式错误（反例）
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-16-新建企业时邮箱格式错误",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": "测试邮箱格式错误",
            "unifiedSocialCreditCode": "91110108MA01XXXX4",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "email": "abc.com",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("param_error")]
    )),
    # 48. 未登录新建（反例）
    FlowStep("anonymous", ApiCase(
        name="TC-ENTERPRISE-17-未登录用户尝试新建企业",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": "未登录测试企业",
            "unifiedSocialCreditCode": "91110108MA01XXXX5",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("not_login")]
    )),
    # 49. 普通员工新建（反例）
    FlowStep("employee", ApiCase(
        name="TC-ENTERPRISE-18-普通员工（无权限）尝试新建企业",
        method="POST",
        path="/oa/enterprise/create",
        body={
            "enterpriseName": "员工测试企业",
            "unifiedSocialCreditCode": "91110108MA01XXXX6",
            "type": 1,
            "contact": "张三",
            "contactPhone": "13800138000",
            "disabledFlag": False
        },
        biz_auto=False,
        assertions=[*_bf("no_permission")]
    )),
    # 50. 查询企业详情（admin）正例 - 需先获取enterpriseId
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-50-分页反查id",
        method="POST",
        path="/oa/enterprise/page/query",
        body={"pageNum": 1, "pageSize": 10, "keywords": ENTERPRISE_NAME},
        save={"/data/list[0]/enterpriseId": "enterprise_id01"},
        assertions=[]
    )),
    # 51. 删除企业（admin）正例 - 放在最后
    FlowStep("admin", ApiCase(
        name="TC-ENTERPRISE-51-管理员成功删除企业",
        method="GET",
        path="/oa/enterprise/delete/${enterprise_id01}",
        assertions=[]
    )),
]

@allure.feature("SmartAdmin · 企业管理")
@allure.story("L2 接口")
@pytest.mark.parametrize("step", FLOW_STEPS, ids=lambda s: s.case.name)
def test_enterprise_crud(role_registry, ctx: ScenarioContext, cleanup_registry, base_url, admin_client, employee_client, step: FlowStep):
    """企业管理CRUD多角色测试"""
    # 根据角色选择客户端
    if step.role == "anonymous":
        client = ApiClient(base_url)  # 未登录客户端
    elif step.role == "admin":
        client = admin_client
    elif step.role == "employee":
        client = employee_client
    else:
        client = role_registry[step.role]
    
    # 执行用例
    result = run_case(client, ctx, step.case)
    
    # 注册清理：创建企业成功后，记录用于后续删除
    if result.passed and step.case.name == "TC-ENTERPRISE-12-管理员成功新建企业":
        # 创建企业成功，但data=null，需要通过分页查询获取ID
        # 这里简化处理：如果后续用例中enterprise_id为空，可能需要重新查询
        pass
    
    # 注册清理：删除企业成功后，如果后续还有同名创建，则不需要清理
    if result.passed and step.case.name == "TC-ENTERPRISE-25-管理员成功删除企业":
        # 删除成功，但可能需要清理其他资源
        pass
    
    # 清理：如果创建了企业并获取到ID，注册删除
    eid = ctx.get("enterprise_id")
    if eid and step.case.name != "TC-ENTERPRISE-25-管理员成功删除企业":
        cleanup_registry.register_delete("/oa/enterprise/delete/{id}", eid)
    
    # 最终断言
    assert result.passed, f"[{step.role}] {step.case.name}: {result.failure_summary}"