"""
AUTO-GENERATED by pytest-case-generator (declarative renderer)
Source mapping:
TC-ENTERPRISE-12-管理员成功新建企业（填写所有必填字段） -> TC-ENTERPRISE-12-管理员成功新建企业（填写所有必填字段）
TC-ENTERPRISE-13-新建企业时企业名称与已有企业重复 -> TC-ENTERPRISE-13-新建企业时企业名称与已有企业重复
TC-ENTERPRISE-14-新建企业时缺少必填字段（企业名称） -> TC-ENTERPRISE-14-新建企业时缺少必填字段（企业名称）
TC-ENTERPRISE-15-新建企业时联系人电话格式错误 -> TC-ENTERPRISE-15-新建企业时联系人电话格式错误
TC-ENTERPRISE-16-未登录用户调用新建企业接口 -> TC-ENTERPRISE-16-未登录用户调用新建企业接口
TC-ENTERPRISE-17-普通员工（无权限）调用新建企业接口 -> TC-ENTERPRISE-17-普通员工（无权限）调用新建企业接口
TC-ENTERPRISE-34-管理员成功给企业添加新员工 -> TC-ENTERPRISE-34-管理员成功给企业添加新员工
TC-ENTERPRISE-35-给一个不存在（或已删除）的企业添加员工 -> TC-ENTERPRISE-35-给一个不存在（或已删除）的企业添加员工
TC-ENTERPRISE-36-重复添加已在该企业下的员工（幂等） -> TC-ENTERPRISE-36-重复添加已在该企业下的员工（幂等）
TC-ENTERPRISE-37-添加员工时员工列表为空 -> TC-ENTERPRISE-37-添加员工时员工列表为空
TC-ENTERPRISE-38-未登录用户调用企业添加员工接口 -> TC-ENTERPRISE-38-未登录用户调用企业添加员工接口
TC-ENTERPRISE-39-普通员工（无权限）调用企业添加员工接口 -> TC-ENTERPRISE-39-普通员工（无权限）调用企业添加员工接口
TC-ENTERPRISE-01-管理员成功分页查询企业列表 -> TC-ENTERPRISE-01-管理员成功分页查询企业列表
TC-ENTERPRISE-27-按企业类型（如外资企业）查询列表 -> TC-ENTERPRISE-27-按企业类型（如外资企业）查询列表
TC-ENTERPRISE-02-带关键字模糊查询企业 -> TC-ENTERPRISE-02-带关键字模糊查询企业
TC-ENTERPRISE-03-带创建时间范围查询企业 -> TC-ENTERPRISE-03-带创建时间范围查询企业
TC-ENTERPRISE-04-按禁用状态过滤查询企业 -> TC-ENTERPRISE-04-按禁用状态过滤查询企业
TC-ENTERPRISE-05-分页查询参数pageSize超过最大值500 -> TC-ENTERPRISE-05-分页查询参数pageSize超过最大值500
TC-ENTERPRISE-06-未登录用户访问企业列表页 -> TC-ENTERPRISE-06-未登录用户访问企业列表页
TC-ENTERPRISE-07-普通员工（无权限）访问企业列表页 -> TC-ENTERPRISE-07-普通员工（无权限）访问企业列表页
TC-ENTERPRISE-08-管理员成功查看企业详情 -> TC-ENTERPRISE-08-管理员成功查看企业详情
TC-ENTERPRISE-09-查看已删除企业的详情 -> TC-ENTERPRISE-09-查看已删除企业的详情
TC-ENTERPRISE-10-未登录用户访问企业详情接口 -> TC-ENTERPRISE-10-未登录用户访问企业详情接口
TC-ENTERPRISE-11-普通员工（无权限）访问企业详情接口 -> TC-ENTERPRISE-11-普通员工（无权限）访问企业详情接口
TC-ENTERPRISE-28-不指定类型查询全部企业列表 -> TC-ENTERPRISE-28-不指定类型查询全部企业列表
TC-ENTERPRISE-29-未登录用户调用按类型查询企业列表接口 -> TC-ENTERPRISE-29-未登录用户调用按类型查询企业列表接口
TC-ENTERPRISE-30-普通员工（无权限）调用按类型查询企业列表接口 -> TC-ENTERPRISE-30-普通员工（无权限）调用按类型查询企业列表接口
TC-ENTERPRISE-31-管理员成功导出企业信息Excel -> TC-ENTERPRISE-31-管理员成功导出企业信息Excel
TC-ENTERPRISE-32-导出企业信息时无符合条件的数据 -> TC-ENTERPRISE-32-导出企业信息时无符合条件的数据
TC-ENTERPRISE-33-未登录用户调用导出企业信息接口 -> TC-ENTERPRISE-33-未登录用户调用导出企业信息接口
TC-ENTERPRISE-40-查询指定企业的全部员工列表 -> TC-ENTERPRISE-40-查询指定企业的全部员工列表
TC-ENTERPRISE-41-查询企业全部员工时企业ID列表为空 -> TC-ENTERPRISE-41-查询企业全部员工时企业ID列表为空
TC-ENTERPRISE-42-未登录用户调用查询企业全部员工接口 -> TC-ENTERPRISE-42-未登录用户调用查询企业全部员工接口
TC-ENTERPRISE-43-普通员工（无权限）调用查询企业全部员工接口 -> TC-ENTERPRISE-43-普通员工（无权限）调用查询企业全部员工接口
TC-ENTERPRISE-44-管理员成功分页查询企业员工 -> TC-ENTERPRISE-44-管理员成功分页查询企业员工
TC-ENTERPRISE-45-带关键字搜索分页查询企业员工 -> TC-ENTERPRISE-45-带关键字搜索分页查询企业员工
TC-ENTERPRISE-46-分页查询企业员工缺少必填参数enterpriseId -> TC-ENTERPRISE-46-分页查询企业员工缺少必填参数enterpriseId
TC-ENTERPRISE-47-未登录用户调用分页查询企业员工接口 -> TC-ENTERPRISE-47-未登录用户调用分页查询企业员工接口
TC-ENTERPRISE-48-普通员工（无权限）调用分页查询企业员工接口 -> TC-ENTERPRISE-48-普通员工（无权限）调用分页查询企业员工接口
TC-ENTERPRISE-18-管理员成功编辑企业信息 -> TC-ENTERPRISE-18-管理员成功编辑企业信息
TC-ENTERPRISE-19-编辑一个不存在（或已删除）的企业 -> TC-ENTERPRISE-19-编辑一个不存在（或已删除）的企业
TC-ENTERPRISE-20-编辑企业时将名称改为与其他企业重复 -> TC-ENTERPRISE-20-编辑企业时将名称改为与其他企业重复
TC-ENTERPRISE-21-未登录用户调用编辑企业接口 -> TC-ENTERPRISE-21-未登录用户调用编辑企业接口
TC-ENTERPRISE-22-普通员工（无权限）调用编辑企业接口 -> TC-ENTERPRISE-22-普通员工（无权限）调用编辑企业接口
TC-ENTERPRISE-49-管理员成功从企业移除员工 -> TC-ENTERPRISE-49-管理员成功从企业移除员工
TC-ENTERPRISE-50-移除员工时企业不存在（或已删除） -> TC-ENTERPRISE-50-移除员工时企业不存在（或已删除）
TC-ENTERPRISE-51-移除员工时员工列表为空 -> TC-ENTERPRISE-51-移除员工时员工列表为空
TC-ENTERPRISE-52-未登录用户调用企业删除员工接口 -> TC-ENTERPRISE-52-未登录用户调用企业删除员工接口
TC-ENTERPRISE-53-普通员工（无权限）调用企业删除员工接口 -> TC-ENTERPRISE-53-普通员工（无权限）调用企业删除员工接口
TC-ENTERPRISE-23-管理员成功删除企业 -> TC-ENTERPRISE-23-管理员成功删除企业
TC-ENTERPRISE-24-删除一个不存在（或已删除）的企业 -> TC-ENTERPRISE-24-删除一个不存在（或已删除）的企业
TC-ENTERPRISE-25-未登录用户调用删除企业接口 -> TC-ENTERPRISE-25-未登录用户调用删除企业接口
TC-ENTERPRISE-26-普通员工（无权限）调用删除企业接口 -> TC-ENTERPRISE-26-普通员工（无权限）调用删除企业接口
"""
from __future__ import annotations

import allure
import pytest
from support.api_case import ApiCase, Assertion, FlowStep, run_case
from support.clients.api_client import ApiClient
from support.fixtures.context import ScenarioContext
from support.fixtures.smartadmin import SA_CODES


def _bf(key):
    """动态业务失败断言：探测不到业务码时退化为「msg 存在」断言，避免导入期 None 崩溃。"""
    code = SA_CODES.get(key)
    if code is None:
        print(f"[反例断言降级] 业务码 {key} 未探测到，仅校验 /msg 存在（反例可能白测，请核对）")
        return [Assertion(expected=True, op="exists", field="/msg",
                          reason=f"业务码 {key} 未探测到，退化为仅校验失败信封")]
    return Assertion.biz_fail(code=code) + [Assertion(expected=True, op="exists", field="/msg")]


# 创建类用例的资源清理规则（渲染器按声明生成）
_CLEANUP = {
    'TC-ENTERPRISE-12-管理员成功新建企业（填写所有必填字段）': {
        'id_var': 'enterprise_id',
        'delete_path': '/oa/enterprise/delete/${enterprise_id}',
    },
}


pytestmark = [pytest.mark.smartadmin, pytest.mark.api, pytest.mark.requires_role('admin'), pytest.mark.requires_role('employee')]


FLOW_STEPS: list[FlowStep] = [
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-12-管理员成功新建企业（填写所有必填字段）',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试有限企业A',
            'unifiedSocialCreditCode': '91110108MA01W1234X',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-13-新建企业时企业名称与已有企业重复',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试有限企业A',
            'unifiedSocialCreditCode': '91110108MA01W9999X',
            'type': 1,
            'contact': '李四',
            'contactPhone': '13900139000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('enterprise_name_duplicate')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-14-新建企业时缺少必填字段（企业名称）',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'unifiedSocialCreditCode': '91110108MA01W5678X',
            'type': 1,
            'contact': '王五',
            'contactPhone': '13700137000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-15-新建企业时联系人电话格式错误',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试格式错误企业',
            'unifiedSocialCreditCode': '91110108MA01W1234Y',
            'type': 1,
            'contact': '赵六',
            'contactPhone': '1234567',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-16-未登录用户调用新建企业接口',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '未登录测试企业',
            'unifiedSocialCreditCode': '91110108MA01W0000X',
            'type': 1,
            'contact': '测试',
            'contactPhone': '13000000000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-17-普通员工（无权限）调用新建企业接口',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '无权限测试企业',
            'unifiedSocialCreditCode': '91110108MA01W7777X',
            'type': 1,
            'contact': '测试',
            'contactPhone': '13600000000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-34-管理员成功给企业添加新员工',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-35-给一个不存在（或已删除）的企业添加员工',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': 99999999, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-36-重复添加已在该企业下的员工（幂等）',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-37-添加员工时员工列表为空',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': []},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-38-未登录用户调用企业添加员工接口',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-39-普通员工（无权限）调用企业添加员工接口',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-01-管理员成功分页查询企业列表',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10},
        save={'/data/list[0]/enterpriseId': 'enterprise_id'},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
            Assertion(field='/data/list', op='exists', expected=True),
            Assertion(field='/data/total', op='exists', expected=True),
            Assertion(field='/data/pageNum', op='exists', expected=True),
            Assertion(field='/data/pageSize', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-27-按企业类型（如外资企业）查询列表',
        method='GET',
        path='/oa/enterprise/query/list',
        params={'type': 2},
        save={'/data[0]/enterpriseId': 'list_enterprise_id'},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-02-带关键字模糊查询企业',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10, 'keywords': '测试'},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-03-带创建时间范围查询企业',
        method='POST',
        path='/oa/enterprise/page/query',
        body={
            'pageNum': 1,
            'pageSize': 10,
            'startTime': '2023-01-01',
            'endTime': '2023-12-31',
        },
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-04-按禁用状态过滤查询企业',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10, 'disabledFlag': True},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-05-分页查询参数pageSize超过最大值500',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 501},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-06-未登录用户访问企业列表页',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-07-普通员工（无权限）访问企业列表页',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-08-管理员成功查看企业详情',
        method='GET',
        path='/oa/enterprise/get/${enterprise_id}',
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/enterpriseName', op='exists', expected=True),
            Assertion(field='/data/unifiedSocialCreditCode', op='exists', expected=True),
            Assertion(field='/data/type', op='exists', expected=True),
            Assertion(field='/data/contact', op='exists', expected=True),
            Assertion(field='/data/contactPhone', op='exists', expected=True),
            Assertion(field='/data/email', op='exists', expected=True),
            Assertion(field='/data/provinceName', op='exists', expected=True),
            Assertion(field='/data/cityName', op='exists', expected=True),
            Assertion(field='/data/districtName', op='exists', expected=True),
            Assertion(field='/data/address', op='exists', expected=True),
            Assertion(field='/data/disabledFlag', op='exists', expected=True),
            Assertion(field='/data/createUserName', op='exists', expected=True),
            Assertion(field='/data/createTime', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-09-查看已删除企业的详情',
        method='GET',
        path='/oa/enterprise/get/99999999',
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-10-未登录用户访问企业详情接口',
        method='GET',
        path='/oa/enterprise/get/${enterprise_id}',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-11-普通员工（无权限）访问企业详情接口',
        method='GET',
        path='/oa/enterprise/get/${enterprise_id}',
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-28-不指定类型查询全部企业列表',
        method='GET',
        path='/oa/enterprise/query/list',
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='exists', expected=True),
        ],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-29-未登录用户调用按类型查询企业列表接口',
        method='GET',
        path='/oa/enterprise/query/list',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-30-普通员工（无权限）调用按类型查询企业列表接口',
        method='GET',
        path='/oa/enterprise/query/list',
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-31-管理员成功导出企业信息Excel',
        method='POST',
        path='/oa/enterprise/exportExcel',
        biz_auto=True,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-32-导出企业信息时无符合条件的数据',
        method='POST',
        path='/oa/enterprise/exportExcel',
        body={'keywords': '不存在的关键字_无数据_1234567890'},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-33-未登录用户调用导出企业信息接口',
        method='POST',
        path='/oa/enterprise/exportExcel',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-40-查询指定企业的全部员工列表',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': ['${enterprise_id}']},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-41-查询企业全部员工时企业ID列表为空',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': []},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='eq', expected=[]),
        ],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-42-未登录用户调用查询企业全部员工接口',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': ['${enterprise_id}']},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-43-普通员工（无权限）调用查询企业全部员工接口',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': ['${enterprise_id}']},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-44-管理员成功分页查询企业员工',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10, 'enterpriseId': '${enterprise_id}'},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
            Assertion(field='/data/total', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-45-带关键字搜索分页查询企业员工',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={
            'pageNum': 1,
            'pageSize': 10,
            'enterpriseId': '${enterprise_id}',
            'keyword': '张',
        },
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-46-分页查询企业员工缺少必填参数enterpriseId',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-47-未登录用户调用分页查询企业员工接口',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10, 'enterpriseId': '${enterprise_id}'},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-48-普通员工（无权限）调用分页查询企业员工接口',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10, 'enterpriseId': '${enterprise_id}'},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-18-管理员成功编辑企业信息',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': '${enterprise_id}',
            'enterpriseName': '测试有限企业A',
            'unifiedSocialCreditCode': '91110108MA01W1234X',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13900139000',
            'disabledFlag': False,
        },
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-19-编辑一个不存在（或已删除）的企业',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': 99999999,
            'enterpriseName': '不存在的企业',
            'unifiedSocialCreditCode': '91110108MA01W1234X',
            'type': 1,
            'contact': '测试',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-20-编辑企业时将名称改为与其他企业重复',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': '${enterprise_id}',
            'enterpriseName': '其他已存在企业名称',
            'unifiedSocialCreditCode': '91110108MA01W1234X',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13900139000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('enterprise_name_duplicate')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-21-未登录用户调用编辑企业接口',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': '${enterprise_id}',
            'enterpriseName': '未登录编辑',
            'unifiedSocialCreditCode': '91110108MA01W1234X',
            'type': 1,
            'contact': '测试',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-22-普通员工（无权限）调用编辑企业接口',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': '${enterprise_id}',
            'enterpriseName': '无权限编辑',
            'unifiedSocialCreditCode': '91110108MA01W1234X',
            'type': 1,
            'contact': '测试',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-49-管理员成功从企业移除员工',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-50-移除员工时企业不存在（或已删除）',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': 99999999, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-51-移除员工时员工列表为空',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': []},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-52-未登录用户调用企业删除员工接口',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-53-普通员工（无权限）调用企业删除员工接口',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': '${enterprise_id}', 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-23-管理员成功删除企业',
        method='GET',
        path='/oa/enterprise/delete/${enterprise_id}',
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/ok', op='eq', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-24-删除一个不存在（或已删除）的企业',
        method='GET',
        path='/oa/enterprise/delete/99999999',
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-25-未登录用户调用删除企业接口',
        method='GET',
        path='/oa/enterprise/delete/${enterprise_id}',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-26-普通员工（无权限）调用删除企业接口',
        method='GET',
        path='/oa/enterprise/delete/${enterprise_id}',
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
]

@allure.feature('企业管理 · 企业档案与员工管理')
@allure.story('企业档案与员工管理全生命周期接口测试')
@pytest.mark.parametrize("step", FLOW_STEPS, ids=lambda s: s.case.name)
def test_enterprise_role_flow(role_registry, ctx: ScenarioContext, cleanup_registry, base_url, admin_client, step: FlowStep):
    if step.role == "anonymous":
        client = ApiClient(base_url)
    elif step.role == "admin":
        client = admin_client
    else:
        client = role_registry[step.role]
    result = run_case(client, ctx, step.case)
    if result.passed and step.case.name in _CLEANUP:
        rule = _CLEANUP[step.case.name]
        cid = ctx.get(rule["id_var"])
        if cid is not None:
            cleanup_registry.register_delete(rule["delete_path"], cid)
    assert result.passed, f"[{step.role}] {step.case.name}: {result.failure_summary}"
