"""
AUTO-GENERATED by pytest-case-generator (declarative renderer)
Source mapping:
TC-ENTERPRISE-12-正常新建企业（填写所有必填字段） -> TC-ENTERPRISE-12-正常新建企业（填写所有必填字段）
TC-ENTERPRISE-13-新建企业时企业名称重复 -> TC-ENTERPRISE-13-新建企业时企业名称重复
TC-ENTERPRISE-14-新建企业时必填字段缺失 -> TC-ENTERPRISE-14-新建企业时必填字段缺失
TC-ENTERPRISE-15-新建企业时联系人电话格式错误 -> TC-ENTERPRISE-15-新建企业时联系人电话格式错误
TC-ENTERPRISE-16-未登录状态下尝试新建企业 -> TC-ENTERPRISE-16-未登录状态下尝试新建企业
TC-ENTERPRISE-17-普通员工尝试新建企业 -> TC-ENTERPRISE-17-普通员工尝试新建企业
TC-ENTERPRISE-35-给不存在的企业添加员工 -> TC-ENTERPRISE-35-给不存在的企业添加员工
TC-ENTERPRISE-38-未登录状态下尝试添加企业员工 -> TC-ENTERPRISE-38-未登录状态下尝试添加企业员工
TC-ENTERPRISE-39-普通员工尝试添加企业员工 -> TC-ENTERPRISE-39-普通员工尝试添加企业员工
TC-ENTERPRISE-01-正常分页查询企业列表 -> TC-ENTERPRISE-01-正常分页查询企业列表
TC-ENTERPRISE-02-带关键字模糊查询企业 -> TC-ENTERPRISE-02-带关键字模糊查询企业
TC-ENTERPRISE-03-带创建时间范围查询企业 -> TC-ENTERPRISE-03-带创建时间范围查询企业
TC-ENTERPRISE-04-带禁用状态过滤查询企业 -> TC-ENTERPRISE-04-带禁用状态过滤查询企业
TC-ENTERPRISE-05-分页查询时输入非法分页参数（pageSize > 500） -> TC-ENTERPRISE-05-分页查询时输入非法分页参数（pageSize > 500）
TC-ENTERPRISE-06-未登录状态下访问企业管理列表页 -> TC-ENTERPRISE-06-未登录状态下访问企业管理列表页
TC-ENTERPRISE-07-普通员工访问企业管理列表页 -> TC-ENTERPRISE-07-普通员工访问企业管理列表页
TC-ENTERPRISE-12-分页反查新建企业ID -> TC-ENTERPRISE-12-分页反查新建企业ID
TC-ENTERPRISE-08-正常查看企业详情 -> TC-ENTERPRISE-08-正常查看企业详情
TC-ENTERPRISE-10-未登录状态下查看企业详情 -> TC-ENTERPRISE-10-未登录状态下查看企业详情
TC-ENTERPRISE-11-普通员工查看企业详情 -> TC-ENTERPRISE-11-普通员工查看企业详情
TC-ENTERPRISE-34-正常给企业添加员工 -> TC-ENTERPRISE-34-正常给企业添加员工
TC-ENTERPRISE-36-添加已存在的员工（幂等操作） -> TC-ENTERPRISE-36-添加已存在的员工（幂等操作）
TC-ENTERPRISE-37-添加员工时员工列表为空 -> TC-ENTERPRISE-37-添加员工时员工列表为空
TC-ENTERPRISE-23-正常删除企业 -> TC-ENTERPRISE-23-正常删除企业
TC-ENTERPRISE-09-查看不存在（或已删除）企业的详情 -> TC-ENTERPRISE-09-查看不存在（或已删除）企业的详情
TC-ENTERPRISE-27-按指定类型查询企业列表 -> TC-ENTERPRISE-27-按指定类型查询企业列表
TC-ENTERPRISE-28-不指定类型查询全部企业列表 -> TC-ENTERPRISE-28-不指定类型查询全部企业列表
TC-ENTERPRISE-29-未登录状态下查询企业列表 -> TC-ENTERPRISE-29-未登录状态下查询企业列表
TC-ENTERPRISE-30-普通员工查询企业列表 -> TC-ENTERPRISE-30-普通员工查询企业列表
TC-ENTERPRISE-40-查询指定企业的全部员工 -> TC-ENTERPRISE-40-查询指定企业的全部员工
TC-ENTERPRISE-41-查询企业全部员工时企业ID列表为空 -> TC-ENTERPRISE-41-查询企业全部员工时企业ID列表为空
TC-ENTERPRISE-42-未登录状态下查询企业全部员工 -> TC-ENTERPRISE-42-未登录状态下查询企业全部员工
TC-ENTERPRISE-43-普通员工查询企业全部员工 -> TC-ENTERPRISE-43-普通员工查询企业全部员工
TC-ENTERPRISE-44-正常分页查询企业员工 -> TC-ENTERPRISE-44-正常分页查询企业员工
TC-ENTERPRISE-45-带关键字搜索分页查询企业员工 -> TC-ENTERPRISE-45-带关键字搜索分页查询企业员工
TC-ENTERPRISE-46-分页查询企业员工时缺少必填参数 enterpriseId -> TC-ENTERPRISE-46-分页查询企业员工时缺少必填参数 enterpriseId
TC-ENTERPRISE-47-未登录状态下分页查询企业员工 -> TC-ENTERPRISE-47-未登录状态下分页查询企业员工
TC-ENTERPRISE-48-普通员工分页查询企业员工 -> TC-ENTERPRISE-48-普通员工分页查询企业员工
TC-ENTERPRISE-31-正常导出企业信息 -> TC-ENTERPRISE-31-正常导出企业信息
TC-ENTERPRISE-32-导出企业信息时无数据 -> TC-ENTERPRISE-32-导出企业信息时无数据
TC-ENTERPRISE-33-未登录状态下尝试导出企业信息 -> TC-ENTERPRISE-33-未登录状态下尝试导出企业信息
TC-ENTERPRISE-18-正常编辑企业信息 -> TC-ENTERPRISE-18-正常编辑企业信息
TC-ENTERPRISE-19-编辑不存在（或已删除）的企业 -> TC-ENTERPRISE-19-编辑不存在（或已删除）的企业
TC-ENTERPRISE-20-编辑企业时将名称改为与其他企业重复 -> TC-ENTERPRISE-20-编辑企业时将名称改为与其他企业重复
TC-ENTERPRISE-21-未登录状态下尝试编辑企业 -> TC-ENTERPRISE-21-未登录状态下尝试编辑企业
TC-ENTERPRISE-22-普通员工尝试编辑企业 -> TC-ENTERPRISE-22-普通员工尝试编辑企业
TC-ENTERPRISE-49-正常从企业移除员工 -> TC-ENTERPRISE-49-正常从企业移除员工
TC-ENTERPRISE-50-移除员工时企业不存在 -> TC-ENTERPRISE-50-移除员工时企业不存在
TC-ENTERPRISE-51-移除员工时员工列表为空 -> TC-ENTERPRISE-51-移除员工时员工列表为空
TC-ENTERPRISE-52-未登录状态下尝试移除企业员工 -> TC-ENTERPRISE-52-未登录状态下尝试移除企业员工
TC-ENTERPRISE-53-普通员工尝试移除企业员工 -> TC-ENTERPRISE-53-普通员工尝试移除企业员工
TC-ENTERPRISE-24-删除不存在（或已删除）的企业 -> TC-ENTERPRISE-24-删除不存在（或已删除）的企业
TC-ENTERPRISE-25-未登录状态下尝试删除企业 -> TC-ENTERPRISE-25-未登录状态下尝试删除企业
TC-ENTERPRISE-26-普通员工尝试删除企业 -> TC-ENTERPRISE-26-普通员工尝试删除企业
"""
from __future__ import annotations

import allure
import pytest
from support.api_case import ApiCase, Assertion, FlowStep, run_case
from support.clients.api_client import ApiClient
from support.fixtures.context import ScenarioContext
from support.fixtures.smartadmin import SA_CODES


def _bf(key):
    """动态业务失败断言：探测不到业务码时退化为「msg 存在」断言，避免导入期 None 崩溃。"""
    code = SA_CODES.get(key)
    if code is None:
        print(f"[反例断言降级] 业务码 {key} 未探测到，仅校验 /msg 存在（反例可能白测，请核对）")
        return [Assertion(expected=True, op="exists", field="/msg",
                          reason=f"业务码 {key} 未探测到，退化为仅校验失败信封")]
    return Assertion.biz_fail(code=code) + [Assertion(expected=True, op="exists", field="/msg")]


# 创建类用例的资源清理规则（渲染器按声明生成）
_CLEANUP = {
    'TC-ENTERPRISE-12-正常新建企业（填写所有必填字段）': {
        'id_var': 'new_enterprise_id',
        'delete_path': '/oa/enterprise/delete/${new_enterprise_id}',
    },
}


pytestmark = [pytest.mark.smartadmin, pytest.mark.api, pytest.mark.requires_role('admin'), pytest.mark.requires_role('employee')]


FLOW_STEPS: list[FlowStep] = [
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-12-正常新建企业（填写所有必填字段）',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试科技有限公司',
            'unifiedSocialCreditCode': '91110108MA01XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='eq', expected=None),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-13-新建企业时企业名称重复',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试科技有限公司',
            'unifiedSocialCreditCode': '91110108MA01XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('enterprise_name_duplicate')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-14-新建企业时必填字段缺失',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'unifiedSocialCreditCode': '91110108MA01XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-15-新建企业时联系人电话格式错误',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试企业电话错误',
            'unifiedSocialCreditCode': '91110108MA02XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '1234567890',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-16-未登录状态下尝试新建企业',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试企业',
            'unifiedSocialCreditCode': '91110108MA03XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138001',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-17-普通员工尝试新建企业',
        method='POST',
        path='/oa/enterprise/create',
        body={
            'enterpriseName': '测试企业',
            'unifiedSocialCreditCode': '91110108MA04XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138002',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-35-给不存在的企业添加员工',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': 999999, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-38-未登录状态下尝试添加企业员工',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': 1, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-39-普通员工尝试添加企业员工',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': 1, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-01-正常分页查询企业列表',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
            Assertion(field='/data/total', op='gt', expected=0),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-02-带关键字模糊查询企业',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10, 'keywords': '科技'},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
            Assertion(field='/data/total', op='gt', expected=0),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-03-带创建时间范围查询企业',
        method='POST',
        path='/oa/enterprise/page/query',
        body={
            'pageNum': 1,
            'pageSize': 10,
            'startTime': '2024-01-01',
            'endTime': '2024-01-31',
        },
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-04-带禁用状态过滤查询企业',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10, 'disabledFlag': True},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-05-分页查询时输入非法分页参数（pageSize > 500）',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 501},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-06-未登录状态下访问企业管理列表页',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-07-普通员工访问企业管理列表页',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-12-分页反查新建企业ID',
        method='POST',
        path='/oa/enterprise/page/query',
        body={'pageNum': 1, 'pageSize': 10, 'keywords': '测试科技有限公司'},
        save={'/data/list[0]/enterpriseId': 'new_enterprise_id'},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/total', op='gt', expected=0),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-08-正常查看企业详情',
        method='GET',
        path='/oa/enterprise/get/${new_enterprise_id}',
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/enterpriseId', op='exists', expected=True),
            Assertion(field='/data/enterpriseName', op='eq', expected='测试科技有限公司'),
        ],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-10-未登录状态下查看企业详情',
        method='GET',
        path='/oa/enterprise/get/${new_enterprise_id}',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-11-普通员工查看企业详情',
        method='GET',
        path='/oa/enterprise/get/${new_enterprise_id}',
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-34-正常给企业添加员工',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${new_enterprise_id}', 'employeeIdList': [1001, 1002]},
        biz_auto=False,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-36-添加已存在的员工（幂等操作）',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${new_enterprise_id}', 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-37-添加员工时员工列表为空',
        method='POST',
        path='/oa/enterprise/employee/add',
        body={'enterpriseId': '${new_enterprise_id}', 'employeeIdList': []},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-23-正常删除企业',
        method='GET',
        path='/oa/enterprise/delete/${new_enterprise_id}',
        biz_auto=False,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-09-查看不存在（或已删除）企业的详情',
        method='GET',
        path='/oa/enterprise/get/999999',
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-27-按指定类型查询企业列表',
        method='GET',
        path='/oa/enterprise/query/list',
        params={'type': 1},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-28-不指定类型查询全部企业列表',
        method='GET',
        path='/oa/enterprise/query/list',
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='exists', expected=True),
        ],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-29-未登录状态下查询企业列表',
        method='GET',
        path='/oa/enterprise/query/list',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-30-普通员工查询企业列表',
        method='GET',
        path='/oa/enterprise/query/list',
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-40-查询指定企业的全部员工',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': ['${new_enterprise_id}']},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-41-查询企业全部员工时企业ID列表为空',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': []},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data', op='eq', expected=[]),
        ],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-42-未登录状态下查询企业全部员工',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': [1]},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-43-普通员工查询企业全部员工',
        method='POST',
        path='/oa/enterprise/employee/list',
        body={'enterpriseIdList': [1]},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-44-正常分页查询企业员工',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10, 'enterpriseId': '${new_enterprise_id}'},
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-45-带关键字搜索分页查询企业员工',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={
            'pageNum': 1,
            'pageSize': 10,
            'enterpriseId': '${new_enterprise_id}',
            'keyword': '张',
        },
        biz_auto=False,
        assertions=[
            Assertion(field='/code', op='eq', expected=0),
            Assertion(field='/data/list', op='exists', expected=True),
        ],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-46-分页查询企业员工时缺少必填参数 enterpriseId',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-47-未登录状态下分页查询企业员工',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10, 'enterpriseId': 1},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-48-普通员工分页查询企业员工',
        method='POST',
        path='/oa/enterprise/employee/queryPage',
        body={'pageNum': 1, 'pageSize': 10, 'enterpriseId': 1},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-31-正常导出企业信息',
        method='POST',
        path='/oa/enterprise/exportExcel',
        body={'keywords': '测试科技有限公司'},
        biz_auto=False,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-32-导出企业信息时无数据',
        method='POST',
        path='/oa/enterprise/exportExcel',
        body={'keywords': '不存在的企业名称XYZ'},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-33-未登录状态下尝试导出企业信息',
        method='POST',
        path='/oa/enterprise/exportExcel',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-18-正常编辑企业信息',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': '${new_enterprise_id}',
            'enterpriseName': '测试科技有限公司',
            'unifiedSocialCreditCode': '91110108MA01XXXXX',
            'type': 1,
            'contact': '李四',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-19-编辑不存在（或已删除）的企业',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': 999999,
            'enterpriseName': '测试企业',
            'unifiedSocialCreditCode': '91110108MA05XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138003',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-20-编辑企业时将名称改为与其他企业重复',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': '${new_enterprise_id}',
            'enterpriseName': '测试科技有限公司',
            'unifiedSocialCreditCode': '91110108MA01XXXXX',
            'type': 1,
            'contact': '李四',
            'contactPhone': '13800138000',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('enterprise_name_duplicate')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-21-未登录状态下尝试编辑企业',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': 1,
            'enterpriseName': '测试企业',
            'unifiedSocialCreditCode': '91110108MA06XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138004',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-22-普通员工尝试编辑企业',
        method='POST',
        path='/oa/enterprise/update',
        body={
            'enterpriseId': 1,
            'enterpriseName': '测试企业',
            'unifiedSocialCreditCode': '91110108MA07XXXXX',
            'type': 1,
            'contact': '张三',
            'contactPhone': '13800138005',
            'disabledFlag': False,
        },
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-49-正常从企业移除员工',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': '${new_enterprise_id}', 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[Assertion(field='/code', op='eq', expected=0)],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-50-移除员工时企业不存在',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': 999999, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-51-移除员工时员工列表为空',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': '${new_enterprise_id}', 'employeeIdList': []},
        biz_auto=False,
        assertions=[*_bf('param_error')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-52-未登录状态下尝试移除企业员工',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': 1, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-53-普通员工尝试移除企业员工',
        method='POST',
        path='/oa/enterprise/employee/delete',
        body={'enterpriseId': 1, 'employeeIdList': [1001]},
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
    FlowStep('admin', ApiCase(
        name='TC-ENTERPRISE-24-删除不存在（或已删除）的企业',
        method='GET',
        path='/oa/enterprise/delete/999999',
        biz_auto=False,
        assertions=[*_bf('enterprise_not_exist')],
    )),
    FlowStep('anonymous', ApiCase(
        name='TC-ENTERPRISE-25-未登录状态下尝试删除企业',
        method='GET',
        path='/oa/enterprise/delete/1',
        biz_auto=False,
        assertions=[*_bf('not_login')],
    )),
    FlowStep('employee', ApiCase(
        name='TC-ENTERPRISE-26-普通员工尝试删除企业',
        method='GET',
        path='/oa/enterprise/delete/1',
        biz_auto=False,
        assertions=[*_bf('no_permission')],
    )),
]

@allure.feature('SmartAdmin OA · 企业管理')
@allure.story('企业档案与员工管理全链路接口测试')
@pytest.mark.parametrize("step", FLOW_STEPS, ids=lambda s: s.case.name)
def test_enterprise_role_flow(role_registry, ctx: ScenarioContext, cleanup_registry, base_url, admin_client, step: FlowStep):
    if step.role == "anonymous":
        client = ApiClient(base_url)
    elif step.role == "admin":
        client = admin_client
    else:
        client = role_registry[step.role]
    result = run_case(client, ctx, step.case)
    if result.passed and step.case.name in _CLEANUP:
        rule = _CLEANUP[step.case.name]
        cid = ctx.get(rule["id_var"])
        if cid is not None:
            cleanup_registry.register_delete(rule["delete_path"], cid)
    assert result.passed, f"[{step.role}] {step.case.name}: {result.failure_summary}"
